language: python
env:
  global:
    - CI=true
# addons:
#   apt_packages:
#     - pandoc
# command to install dependencies

matrix:
  include:
    - os: linux
      python: 3.5
    
    - os: osx
      sudo: required
      language: generic
      
#  Manually install python on osx
before-install: |
  if [[ $TRAVIS_OS_NAME == 'osx' ]]; then

      brew update;
      brew install python3;
      virtualenv venv -p python3;
      source venv/bin/activate;
      
  else
      # Install some custom requirements on Linux
  fi
  
install:
  - pip install . test
script: python tests/supervisor.py
branches:
  only:
    - master